### ISSUE TITLE
How does this compare to react-styleguidist

### ISSUE THREAD

**Issue by pke** [steos/reactcards#11]
https://github.com/sapegin/react-styleguidist seems to also do quite the same, with live edit capabilities even. How do the 2 projects compare?

**Comment by 0xR** [comment]
I don't see unit tests in styleguidist

**Comment by busypeoples** [comment]
Yes, you can run your tests against your components and even reuse them to run as regular cli tests later on. We'll add a section to the documentation, describing how to use your tests with React Cards as well as mocha f.e.
