### ISSUE TITLE
fresh react-create-app install 

### ISSUE THREAD

**Issue by ioRekz** [steos/reactcards#32]
Starting with a fresh react app install using react-scripts 0.8.3, I have the following error 
`ReferenceError: Unknown plugin "react-hot-loader/babel" specified in "base" at 0`

Not familiar with babel so I dont have a clue

**Comment by ioRekz** [comment]
My bad playing with old version of node

**Comment by superdtx** [comment]
@ioRekz Which Node version were you using. I got the same problem with Node v8.

**Comment by ioRekz** [comment]
I don't remember as it was a long time ago.
Did you check the example repo ? https://github.com/steos/reactcards-example/tree/master/create-react-app-example
