### ISSUE TITLE
Missing lodash dependency

### ISSUE THREAD

**Issue by a-c-m** [steos/reactcards#9]
If you try to run this without lodash installed globally, it will fail.

**Comment by steos** [comment]
This works fine for me on a fresh trusty install without any lodash? What problem do you have specifically?

**Comment by a-c-m** [comment]
Are you sure you don't have lodash installed globally?

```
webpack-dev-server --config examples/webpack.config.js --content-base ./public/ --host 0.0.0.0 --port 1234 --hot --inline
http://0.0.0.0:1234/
webpack result is served from /
content is served from /Users/alex/dev/reactcards-original/public
Hash: 220c3b612b91719a572a
Version: webpack 1.13.1
Time: 7590ms
 Asset     Size  Chunks             Chunk Names
app.js  1.84 MB       0  [emitted]  main
chunk    {0} app.js (main) 1.71 MB [rendered]
    [0] multi main 76 bytes {0} [built]
    ....

ERROR in ./src/Container.js
Module not found: Error: Cannot resolve module 'lodash' in /Users/alex/dev/reactcards-original/src
 @ ./src/Container.js 17:14-31
```

Look in `./src/Container.js` - line 3 is `import { find, map } from 'lodash'` but you have no lodash mentioned in the package.json.

**Comment by steos** [comment]
I didn't realize that we've added lodash as a dependency. Not sure why I didn't see any error though. Thanks!
